### ISSUE TITLE
Class 'App\Http\Controllers\IPay88\Payment\Request' not found 

### ISSUE THREAD

**Issue by sadeknurul** [aa6my/ipay#3]
Hi there, I am getting this error
`Class 'App\Http\Controllers\IPay88\Payment\Request' not found ` 
please guide me on how do I solve the issue?
Thanks
Sadek

**Comment by shiroamada** [comment]
@sadeknurul namespace not correct.
`IPay88\Payment\Request` not `App\Http\Controllers\IPay88\Payment\Request`
